/*
 * Books API
 *
 * This web service offers information on books
 *
 * API version: 0.1.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AuthorAuthorIdDelete",
		strings.ToUpper("Delete"),
		"/author/{authorId}",
		AuthorAuthorIdDelete,
	},

	Route{
		"AuthorAuthorIdGet",
		strings.ToUpper("Get"),
		"/author/{authorId}",
		AuthorAuthorIdGet,
	},

	Route{
		"AuthorAuthorIdPut",
		strings.ToUpper("Put"),
		"/author/{authorId}",
		AuthorAuthorIdPut,
	},

	Route{
		"AuthorPost",
		strings.ToUpper("Post"),
		"/author/",
		AuthorPost,
	},

	Route{
		"BooksBookIdDelete",
		strings.ToUpper("Delete"),
		"/books/{bookId}",
		BooksBookIdDelete,
	},

	Route{
		"BooksBookIdGet",
		strings.ToUpper("Get"),
		"/books/{bookId}",
		BooksBookIdGet,
	},

	Route{
		"BooksBookIdPut",
		strings.ToUpper("Put"),
		"/books/{bookId}",
		BooksBookIdPut,
	},

	Route{
		"BooksPost",
		strings.ToUpper("Post"),
		"/books/",
		BooksPost,
	},

	Route{
		"PublisherPost",
		strings.ToUpper("Post"),
		"/publisher/",
		PublisherPost,
	},

	Route{
		"PublisherPublisherIdDelete",
		strings.ToUpper("Delete"),
		"/publisher/{publisherId}",
		PublisherPublisherIdDelete,
	},

	Route{
		"PublisherPublisherIdGet",
		strings.ToUpper("Get"),
		"/publisher/{publisherId}",
		PublisherPublisherIdGet,
	},

	Route{
		"PublisherPublisherIdPut",
		strings.ToUpper("Put"),
		"/publisher/{publisherId}",
		PublisherPublisherIdPut,
	},
}
